<script setup lang="ts">
import { computed, onMounted, reactive, shallowRef, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { api, queryString, type GroupConfig, type Pagination } from "../services/api";
import { useUrlState } from "../composables/useUrlState";
import { useAppStore } from "../stores/app";
import { formatDateTime } from "../utils/format";

type RangeKey = "24h" | "7d" | "30d" | "custom";
type UsageSummary = { calls:number; succeeded:number; failed:number; cancelled:number; durationMs:number; inputTokens:number; outputTokens:number; totalTokens:number; usageCount:number; images:number; billingCount:number; charges:Record<string,number>; successRate:number|null; averageLatencyMs:number|null; p95LatencyUpperBoundMs:number|null; billingCoverage:number|null; usageCoverage:number|null };
type AnalyticsData = { options:{models:Array<{id:string;label:string}>;purposes:string[]}; summary:UsageSummary; series:Array<UsageSummary & {time:string}>; startedAt:string|null; timezone:string; retention:{detailDays:number;aggregateDays:number} };
type RequestRecord = { id:string; operationId:string; groupId:string; modelId:string; model:string; purpose:string; probe:boolean; startedAt:number; durationMs:number; status:"succeeded"|"failed"|"cancelled"; inputTokens:number|null; outputTokens:number|null; totalTokens:number|null; images:number; actualAmount:number|null; currency:string|null };
const route=useRoute(),router=useRouter(),app=useAppStore();
const ranges:Array<{key:RangeKey;label:string}>=[{key:"24h",label:"近 24 小时"},{key:"7d",label:"近 7 天"},{key:"30d",label:"近 30 天"},{key:"custom",label:"自定义"}];
const range=computed<RangeKey>({get:()=>ranges.some(r=>r.key===route.query.range)?route.query.range as RangeKey:"24h",set:value=>updateQuery({range:value})});
const filters=reactive({groupId:typeof route.query.analyticsGroup==="string"?route.query.analyticsGroup:"",modelId:typeof route.query.modelId==="string"?route.query.modelId:"",purpose:typeof route.query.purpose==="string"?route.query.purpose:"",includeProbes:route.query.probes==="1",fromDate:typeof route.query.from==="string"?route.query.from.slice(0,10):dateKey(Date.now()-6*86400000),toDate:typeof route.query.to==="string"?route.query.to.slice(0,10):dateKey(Date.now())});
const data=shallowRef<AnalyticsData|null>(null), requests=shallowRef<RequestRecord[]>([]), pagination=reactive<Pagination>({page:1,pageSize:25,total:0,totalPages:1});
useUrlState(pagination,["page","pageSize"],"request");
const loading=shallowRef(false),failed=shallowRef(""),detailLoading=shallowRef(false),trend=shallowRef<"calls"|"tokens"|"durationMs"|"images">("calls");
const purposeLabels:Record<string,string>={reply:"对话",html:"网页生成",image:"图片生成",probe:"检测",summary:"总结",knowledge:"知识",memory:"记忆",broadcast:"播报",reminder:"提醒",background:"后台任务"};
const currentRange=computed(()=>range.value==="custom"?`${filters.fromDate} 至 ${filters.toDate}`:range.value==="24h"?"近 24 小时":range.value==="7d"?"近 7 天":"近 30 天");
const chargeLines=computed(()=>Object.entries(data.value?.summary.charges||{}));
const metricCards=computed(()=>{const summary=data.value?.summary;return [
  {label:"模型请求",value:number(summary?.calls),note:`失败 ${summary?.failed??0} · 取消 ${summary?.cancelled??0}`},
  {label:"成功率",value:summary?.successRate==null?"—":`${(summary.successRate*100).toFixed(1)}%`,note:`成功 ${summary?.succeeded??0} 次`},
  {label:"平均耗时",value:summary?.averageLatencyMs==null?"—":formatLatency(summary.averageLatencyMs),note:`P95 上界 ${summary?.p95LatencyUpperBoundMs==null?"—":formatLatency(summary.p95LatencyUpperBoundMs)}`},
  {label:"Token 用量",value:number(summary?.totalTokens),note:`采集覆盖率 ${percent(summary?.usageCoverage)}`},
  {label:"图片生成",value:number(summary?.images),note:"成功生成数量"},
  {label:"实际计费",value:chargeLines.value.length?chargeLines.value.map(([c,v])=>`${money(v)} ${c}`).join(" · "):"上游未提供",note:`计费数据覆盖率 ${percent(summary?.billingCoverage)}`},
]});
const chartPoints=computed(()=>{const rows=data.value?.series||[],values=rows.map(r=>Number(r[trend.value]||0)),max=Math.max(1,...values);return rows.map((row,i)=>({x:rows.length<2?50:i/(rows.length-1)*100,y:94-values[i]!/max*84,value:values[i]!,time:row.time}));});
const linePath=computed(()=>chartPoints.value.map((point,i)=>`${i?"L":"M"}${point.x},${point.y}`).join(" "));
const areaPath=computed(()=>chartPoints.value.length?`${linePath.value} L 100,100 L 0,100 Z`:"");
const fromTo=computed(()=>{
  const now=Date.now();
  if(range.value==="24h") return {from:now-86400000,to:now};
  if(range.value==="7d"||range.value==="30d") { const end=beijingMidnight(now)+86400000,days=range.value==="7d"?7:30; return {from:end-days*86400000,to:end}; }
  if(!filters.fromDate||!filters.toDate) return {from:now-86400000,to:now};
  return {from:Date.parse(`${filters.fromDate}T00:00:00+08:00`),to:Date.parse(`${addDay(filters.toDate)}T00:00:00+08:00`)};
});
function beijingMidnight(time:number){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(time);const get=(type:string)=>parts.find(p=>p.type===type)?.value||"";return Date.parse(`${get("year")}-${get("month")}-${get("day")}T00:00:00+08:00`);}
function addDay(date:string){const [y,m,d]=date.split("-").map(Number);return new Date(Date.UTC(y!,m!-1,d!+1)).toISOString().slice(0,10);}
function dateKey(time:number){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(time);}
function updateQuery(values:Record<string,string|undefined>){const query={...route.query};for(const [key,value] of Object.entries(values)){if(value)query[key]=value;else delete query[key];}void router.replace({query});}
function applyFilters(){pagination.page=1;updateQuery({analyticsGroup:filters.groupId||undefined,modelId:filters.modelId||undefined,purpose:filters.purpose||undefined,probes:filters.includeProbes?"1":undefined});}
function number(value:number|undefined){return (value??0).toLocaleString("zh-CN");}
function percent(value:number|null|undefined){return value==null?"—":`${(value*100).toFixed(1)}%`;}
function money(value:number){return new Intl.NumberFormat("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:6}).format(value);}
function formatLatency(value:number){return value<1000?`${Math.round(value)} ms`:`${(value/1000).toFixed(2)} s`;}
function rangeLabel(time:string){return range.value==="24h"?`${time.slice(11,13)}:00`:time;}
function statusLabel(status:RequestRecord["status"]){return ({succeeded:"成功",failed:"失败",cancelled:"取消"} as const)[status];}
function statusClass(status:RequestRecord["status"]){return status==="failed"?"danger":status==="cancelled"?"neutral":"";}
function tokenLabel(record:RequestRecord){return record.totalTokens==null?"上游未提供":number(record.totalTokens);}
function chargeLabel(record:RequestRecord){return record.actualAmount==null||!record.currency?"上游未提供":`${money(record.actualAmount)} ${record.currency}`;}
async function load(){loading.value=true;failed.value="";const {from,to}=fromTo.value;const common={from:new Date(from).toISOString(),to:new Date(to).toISOString(),groupId:filters.groupId||undefined,modelId:filters.modelId||undefined,purpose:filters.purpose||undefined,includeProbes:filters.includeProbes?1:undefined};
  try {const [report,detail]=await Promise.all([api<AnalyticsData>(`/api/analytics/summary${queryString(common)}`),api<{items:RequestRecord[];pagination:Pagination}>(`/api/analytics/requests${queryString({...common,page:pagination.page,pageSize:pagination.pageSize})}`)]);data.value=report;requests.value=detail.items;Object.assign(pagination,detail.pagination);}
  catch(error){failed.value=(error as Error).message;app.showToast(failed.value,"error");}
  finally{loading.value=false;}}
function retry(){void load();}
function onDateChange(){pagination.page=1;updateQuery({range:"custom",from:filters.fromDate||undefined,to:filters.toDate||undefined,analyticsGroup:filters.groupId||undefined,modelId:filters.modelId||undefined,purpose:filters.purpose||undefined,probes:filters.includeProbes?"1":undefined});void load();}
watch(()=>[route.query.range,route.query.from,route.query.to,route.query.analyticsGroup,route.query.modelId,route.query.purpose,route.query.probes],()=>{filters.groupId=typeof route.query.analyticsGroup==="string"?route.query.analyticsGroup:"";filters.modelId=typeof route.query.modelId==="string"?route.query.modelId:"";filters.purpose=typeof route.query.purpose==="string"?route.query.purpose:"";filters.includeProbes=route.query.probes==="1";const from=typeof route.query.from==="string"?route.query.from:"",to=typeof route.query.to==="string"?route.query.to:"";if(from&&to){filters.fromDate=from.slice(0,10);filters.toDate=to.slice(0,10);}if(route.query.range==="custom"&&(!filters.fromDate||!filters.toDate)){filters.toDate=dateKey(Date.now());filters.fromDate=dateKey(Date.now()-6*86400000);}pagination.page=1;void load();},{immediate:true});
watch(()=>[pagination.page,pagination.pageSize],()=>{if(data.value)void load();});
</script>
<template>
  <section class="page analytics-page">
    <header class="analytics-head"><div><h2>调用分析</h2><p>记录自上线以来的真实模型请求；不采集提示词或生成内容。</p></div><span class="timezone-label">Asia/Shanghai · 北京时间</span></header>
    <div class="analytics-toolbar panel"><div class="range-tabs" role="tablist" aria-label="统计时间范围"><button v-for="item in ranges" :key="item.key" :class="{active:range===item.key}" role="tab" :aria-selected="range===item.key" @click="range=item.key">{{item.label}}</button></div><template v-if="range==='custom'"><label>开始日期<input v-model="filters.fromDate" type="date" class="input date-input" @change="onDateChange"/></label><label>结束日期<input v-model="filters.toDate" type="date" class="input date-input" @change="onDateChange"/></label></template><label v-if="app.role==='super_admin'" class="filter-field">群<select v-model="filters.groupId" class="select"><option value="">全部授权群</option><option value="" disabled>全局请求包含在总览中</option><option v-for="group in app.groups" :key="group.groupId" :value="group.groupId">{{group.groupName||group.groupId}}</option></select></label><label class="filter-field">模型<select v-model="filters.modelId" class="select"><option value="">全部模型</option><option v-for="model in data?.options.models||[]" :key="model.id" :value="model.id">{{model.label}}</option></select></label><label class="filter-field">用途<select v-model="filters.purpose" class="select"><option value="">全部用途</option><option v-for="purpose in data?.options.purposes||[]" :key="purpose" :value="purpose">{{purposeLabels[purpose]||purpose}}</option></select></label><label class="probe-toggle"><input v-model="filters.includeProbes" type="checkbox"/>包含检测请求</label><button class="btn" :disabled="loading" @click="applyFilters();load()">{{loading?'更新中…':'应用筛选'}}</button></div>
    <div v-if="failed" class="error-state"><strong>调用分析加载失败</strong><span>{{failed}}</span><button class="ghost-btn" @click="retry">重试</button></div>
    <div v-else class="analytics-content" :aria-busy="loading">
      <div v-if="loading" class="loading-line" aria-label="正在加载"/>
      <div class="metric-grid analytics-metrics"><article v-for="metric in metricCards" :key="metric.label" class="metric-tile"><span>{{metric.label}}</span><strong>{{metric.value}}</strong><small>{{metric.note}}</small></article></div>
      <section class="panel trend-panel"><div class="section-head"><div><h3>请求趋势</h3><p>{{currentRange}} · {{data?.summary.calls??0}} 次调用</p></div><div class="view-toggle" role="group" aria-label="趋势指标"><button v-for="item in [{id:'calls',label:'调用'},{id:'tokens',label:'Token'},{id:'durationMs',label:'耗时'},{id:'images',label:'图片'}]" :key="item.id" :class="{active:trend===item.id}" @click="trend=item.id as typeof trend">{{item.label}}</button></div></div><div v-if="!data?.summary.calls" class="empty compact">该时间范围暂无已采集的请求。</div><div v-else class="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" :aria-label="`请求趋势，共${data.summary.calls}次`"><defs><linearGradient id="callArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="var(--accent)" stop-opacity=".24"/><stop offset="100%" stop-color="var(--accent)" stop-opacity="0"/></linearGradient></defs><path :d="areaPath" fill="url(#callArea)"/><path :d="linePath" fill="none" stroke="var(--accent)" stroke-width=".8" vector-effect="non-scaling-stroke"/><line v-for="n in 4" :key="n" x1="0" :y1="n*20" x2="100" :y2="n*20" stroke="var(--line)" stroke-width=".3" vector-effect="non-scaling-stroke"/></svg><div class="chart-axis"><span v-for="point in chartPoints.filter((_,i)=>i===0||i===chartPoints.length-1||i===Math.floor(chartPoints.length/2))" :key="point.time">{{rangeLabel(point.time)}}</span></div></div></section>
      <section class="panel coverage-panel"><div class="coverage-title"><div><h3>用量与计费覆盖</h3><p>金额只统计上游明确返回计费金额及币种的请求。</p></div><span class="period-pill">{{currentRange}}</span></div><div class="coverage-grid"><div><span>Token 数据覆盖</span><strong>{{percent(data?.summary.usageCoverage)}}</strong><small>{{data?.summary.usageCount??0}} / {{data?.summary.calls??0}} 次</small></div><div><span>计费数据覆盖</span><strong>{{percent(data?.summary.billingCoverage)}}</strong><small>{{data?.summary.billingCount??0}} / {{data?.summary.calls??0}} 次</small></div><div><span>上游计费</span><strong v-if="chargeLines.length">{{chargeLines.map(([currency,amount])=>`${money(amount)} ${currency}`).join(' · ')}}</strong><strong v-else>上游未提供</strong><small>不同币种分别汇总，不估算费用</small></div></div><p class="retention-note">采集起始时间：{{data?.startedAt?formatDateTime(data.startedAt):'尚无请求记录'}} · 明细保留 {{data?.retention.detailDays??30}} 天 · 日汇总保留 {{data?.retention.aggregateDays??180}} 天</p></section>
      <section class="panel request-panel"><div class="section-head"><div><h3>请求明细</h3><p>{{pagination.total.toLocaleString()}} 条记录 · 不包含提示词与生成内容</p></div><select v-model.number="pagination.pageSize" class="select page-size"><option :value="25">每页 25 条</option><option :value="50">每页 50 条</option><option :value="100">每页 100 条</option></select></div><div v-if="!requests.length" class="empty compact">暂无请求明细。新增请求会在此处记录。</div><div v-else class="table-wrap"><table><thead><tr><th>时间</th><th>群</th><th>用途</th><th>模型</th><th>状态</th><th>耗时</th><th>Token</th><th>图片</th><th>实际费用</th><th>业务操作</th></tr></thead><tbody><tr v-for="record in requests" :key="record.id"><td>{{formatDateTime(record.startedAt)}}</td><td>{{app.groups.find(g=>g.groupId===record.groupId)?.groupName||record.groupId||'全局'}}</td><td>{{purposeLabels[record.purpose]||record.purpose}}<span v-if="record.probe" class="tag neutral probe-tag">检测</span></td><td><strong>{{record.model}}</strong><small class="muted block">{{record.modelId}}</small></td><td><span class="tag" :class="statusClass(record.status)">{{statusLabel(record.status)}}</span></td><td>{{formatLatency(record.durationMs)}}</td><td>{{tokenLabel(record)}}</td><td>{{record.images||'—'}}</td><td>{{chargeLabel(record)}}</td><td><code>{{record.operationId.slice(0,8)}}</code></td></tr></tbody></table></div><div class="pagination"><button class="ghost-btn" :disabled="pagination.page<=1||detailLoading" @click="pagination.page--;load()">上一页</button><span>第 {{pagination.page}} / {{pagination.totalPages}} 页</span><button class="ghost-btn" :disabled="pagination.page>=pagination.totalPages||detailLoading" @click="pagination.page++;load()">下一页</button></div></section>
    </div>
  </section>
</template>
<style scoped>
.analytics-page{gap:18px}.analytics-head,.coverage-title{display:flex;align-items:center;justify-content:space-between;gap:16px}.analytics-head h2{font-size:24px;margin:0;color:var(--text-strong)}.analytics-head p,.coverage-title p{color:var(--muted);margin:7px 0 0;font-size:13px}.timezone-label,.period-pill{font-size:12px;color:var(--muted);background:var(--surface-soft);padding:8px 10px;border-radius:6px;white-space:nowrap}.analytics-toolbar{display:flex;align-items:center;gap:10px;padding:14px;flex-wrap:wrap}.analytics-toolbar label{display:grid;gap:5px;color:var(--muted);font-size:11px}.range-tabs{display:flex;gap:2px;background:var(--surface-soft);padding:3px;border-radius:7px}.range-tabs button{font-size:12px;color:var(--muted);padding:8px 10px;border-radius:5px;white-space:nowrap}.range-tabs button.active{color:var(--accent-strong);background:var(--surface);box-shadow:var(--shadow-sm);font-weight:600}.filter-field{width:150px}.date-input{min-width:138px}.probe-toggle{display:flex!important;align-items:center;gap:8px!important;min-height:38px;white-space:nowrap}.analytics-content{display:grid;gap:18px}.analytics-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.metric-tile{display:grid;gap:9px;padding:18px 20px;border:1px solid var(--line);border-radius:7px;background:var(--surface)}.metric-tile span,.coverage-grid span{font-size:12px;color:var(--muted)}.metric-tile strong{font-size:23px;color:var(--text-strong);font-weight:650;overflow-wrap:anywhere}.metric-tile small,.coverage-grid small{font-size:11px;color:var(--subtle);line-height:1.5}.trend-panel,.coverage-panel,.request-panel{display:grid;gap:16px}.trend-panel .section-head,.request-panel .section-head{margin:0}.trend-panel h3,.coverage-panel h3,.request-panel h3{font-size:16px;margin:0}.view-toggle{display:flex;gap:2px}.view-toggle button{padding:7px 10px;border-radius:5px;color:var(--muted);font-size:12px}.view-toggle button.active{background:var(--accent-soft);color:var(--accent-strong)}.chart-wrap{height:220px;display:grid;grid-template-rows:1fr auto;padding:8px 4px 0}.chart-wrap svg{width:100%;height:100%;overflow:visible}.chart-axis{display:flex;justify-content:space-between;color:var(--subtle);font-size:11px;padding-top:9px}.coverage-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-block:1px solid var(--line)}.coverage-grid>div{display:grid;gap:7px;padding:17px 18px;border-right:1px solid var(--line)}.coverage-grid>div:last-child{border:0}.coverage-grid strong{font-size:18px;color:var(--text-strong);overflow-wrap:anywhere}.retention-note{font-size:11px;color:var(--subtle);margin:0}.page-size{width:auto;min-width:140px}.probe-tag{margin-left:6px}.pagination{display:flex;align-items:center;justify-content:flex-end;gap:12px;padding-top:10px;font-size:12px;color:var(--muted)}code{font-size:11px;color:var(--muted)}
@media(max-width:1050px){.analytics-toolbar{align-items:end}.range-tabs{width:100%;overflow:auto}.filter-field{flex:1;min-width:130px}.analytics-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:640px){.analytics-head{align-items:start;flex-direction:column}.analytics-head h2{font-size:21px}.analytics-toolbar{padding:12px}.analytics-toolbar>.btn{flex:1}.analytics-metrics{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.metric-tile{padding:14px}.metric-tile strong{font-size:19px}.coverage-grid{grid-template-columns:1fr}.coverage-grid>div{border-right:0;border-bottom:1px solid var(--line);padding:13px 2px}.coverage-grid>div:last-child{border:0}.trend-panel .section-head{align-items:start;flex-direction:column}.table-wrap table{min-width:1120px}.pagination{justify-content:center}}
</style>
