<script setup lang="ts">
import { computed, onMounted, shallowRef, watch } from "vue";
import { useRouter } from "vue-router";
import AdminDialog from "../components/AdminDialog.vue";
import BulkPreviewDialog from "../components/BulkPreviewDialog.vue";
import { api } from "../services/api";
import { useAppStore } from "../stores/app";
const router=useRouter(),app=useAppStore();
const groups=shallowRef<Array<{groupId:string;groupName?:string;enabled?:boolean}>>([]),sourceId=shallowRef(""),targetIds=shallowRef(new Set<string>()),fields=shallowRef(new Set<string>(["replyModelMode","participationMode"])),preview=shallowRef<any>(null),busy=shallowRef(false),error=shallowRef("");
const selectedGroups=computed(()=>groups.value.filter(group=>targetIds.value.has(group.groupId)));
const sections=[
  {title:"回复策略",items:[{id:"replyModelMode",label:"回复模型"},{id:"participationMode",label:"参与方式"},{id:"liveChatDelaySeconds",label:"实时对话延迟"},{id:"triggerKeywords",label:"触发关键词"}]},
  {title:"能力开关",items:[{id:"onlineLookupEnabled",label:"自动查询实时资料"},{id:"visionEnabled",label:"图片理解"},{id:"ambientGroupContextEnabled",label:"短时群聊语境"},{id:"htmlPreviewEnabled",label:"静态网页预览"},{id:"opsAlertsEnabled",label:"运维告警"},{id:"botMuted",label:"机器人静音"}]},
  {title:"排程",items:[{id:"dailyReportEnabled",label:"群聊日报"},{id:"dailyReportTime",label:"日报时间"},{id:"dailyReportDateRule",label:"日报日期规则"},{id:"dailyReportWeekdays",label:"日报星期"},{id:"dailyReportTopUserCount",label:"日报人数"},{id:"holidayCountdownEnabled",label:"节日倒计时"},{id:"holidayCountdownTime",label:"倒计时时间"},{id:"holidayCountdownDateRule",label:"倒计时日期规则"},{id:"holidayCountdownWeekdays",label:"倒计时星期"},{id:"scheduledRemindersEnabled",label:"定时提醒"}]},
];
watch(sourceId, (id) => { const next=new Set(targetIds.value);next.delete(id);targetIds.value=next;preview.value=null; });
function setTarget(id:string,checked:boolean){const next=new Set(targetIds.value);checked?next.add(id):next.delete(id);targetIds.value=next;preview.value=null;}
function setField(id:string,checked:boolean){const next=new Set(fields.value);checked?next.add(id):next.delete(id);fields.value=next;preview.value=null;}
async function load(){try{const result=await api<{groups:Array<{groupId:string;groupName?:string;enabled?:boolean}>}>("/api/groups?includeDisabled=1");groups.value=result.groups;sourceId.value=app.groupId||result.groups[0]?.groupId||"";}catch(e){error.value=(e as Error).message;}}
async function prepare(){if(!sourceId.value||!targetIds.value.size||!fields.value.size)return;busy.value=true;error.value="";try{preview.value=await api("/api/bulk-operations/preview",{method:"POST",body:JSON.stringify({resource:"group-config",action:"copy",sourceGroupId:sourceId.value,ids:[...targetIds.value],fields:[...fields.value]})});}catch(e){error.value=(e as Error).message;app.showToast(error.value,"error");}finally{busy.value=false;}}
async function execute(){if(!preview.value)return;busy.value=true;try{const result=await api<{taskId:string}>("/api/bulk-operations/apply",{method:"POST",body:JSON.stringify({previewId:preview.value.id})});preview.value=null;app.showToast("跨群配置任务已创建");await router.push({path:"/tasks",query:{task:result.taskId}});}catch(e){error.value=(e as Error).message;app.showToast(error.value,"error");}finally{busy.value=false;}}
onMounted(()=>{if(app.role!=="super_admin"){void router.replace("/");return;}void load();});
</script>
<template>
  <section class="page bulk-config-page">
    <header class="bulk-heading"><div><h2>跨群配置</h2><p>选择来源群、目标群和需要复制的字段；身份、权限名单和隐私退出信息不会参与复制。</p></div><span class="super-label">超级管理员</span></header>
    <div v-if="error" class="error-state" role="alert"><strong>无法加载群配置</strong><span>{{error}}</span><button class="ghost-btn" @click="load">重试</button></div>
    <div class="bulk-layout">
      <section class="panel source-panel"><div class="section-head"><div><h3>来源群</h3><p>复制此群当前已保存的配置。</p></div></div><label class="field">选择来源群<select v-model="sourceId" class="select"><option v-for="group in groups" :key="group.groupId" :value="group.groupId">{{group.groupName||group.groupId}}{{group.enabled===false?'（已停用）':''}}</option></select></label><div v-if="sourceId" class="source-summary"><span class="source-icon">群</span><div><strong>{{groups.find(group=>group.groupId===sourceId)?.groupName||sourceId}}</strong><small>{{sourceId}}</small></div></div><div class="notice">复制预览会逐项展示来源字段、目标群当前值和将要应用的值。执行前会重新检查权限和配置版本。</div></section>
      <section class="panel targets-panel"><div class="section-head"><div><h3>目标群</h3><p>选择需要接收配置的群聊。</p></div><button class="link-btn" type="button" @click="targetIds=new Set(groups.filter(group=>group.groupId!==sourceId).map(group=>group.groupId))">全选</button></div><div v-if="groups.filter(group=>group.groupId!==sourceId).length" class="target-list"><label v-for="group in groups.filter(group=>group.groupId!==sourceId)" :key="group.groupId" class="target-row"><span><strong>{{group.groupName||group.groupId}}</strong><small>{{group.groupId}}<span v-if="group.enabled===false" class="tag neutral">已停用</span></small></span><input type="checkbox" :checked="targetIds.has(group.groupId)" @change="setTarget(group.groupId,($event.target as HTMLInputElement).checked)"/></label></div><div v-else class="empty compact">没有可选的目标群。</div><div class="target-count">已选 <strong>{{selectedGroups.length}}</strong> 个目标群</div></section>
      <section class="panel fields-panel"><div class="section-head"><div><h3>复制字段</h3><p>仅复制勾选项。每个目标群会逐项做配置兼容性校验。</p></div></div><div v-for="section in sections" :key="section.title" class="field-section"><h4>{{section.title}}</h4><div class="field-options"><label v-for="item in section.items" :key="item.id" class="field-option"><input type="checkbox" :checked="fields.has(item.id)" @change="setField(item.id,($event.target as HTMLInputElement).checked)"/><span>{{item.label}}</span></label></div></div></section>
    </div>
    <footer class="bulk-footer"><div><strong>{{selectedGroups.length}}</strong> 个目标群 · <strong>{{fields.size}}</strong> 个配置字段<span v-if="!fields.size||!targetIds.size" class="muted"> · 请选择目标和字段</span></div><button class="btn" :disabled="busy||!sourceId||!targetIds.size||!fields.size" @click="prepare">{{busy?'生成预览…':'预览配置变更'}}</button></footer>
    <BulkPreviewDialog v-if="preview" :preview="preview" :busy="busy" @close="preview=null" @execute="execute"/>
  </section>
</template>
<style scoped>
.bulk-config-page{gap:18px}.bulk-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.bulk-heading h2{font-size:24px;color:var(--text-strong);margin:0}.bulk-heading p{font-size:13px;line-height:1.6;color:var(--muted);max-width:820px;margin:8px 0 0}.super-label{padding:7px 10px;background:var(--accent-soft);color:var(--accent-strong);font-size:11px;font-weight:600;border-radius:5px;white-space:nowrap}.bulk-layout{display:grid;grid-template-columns:minmax(230px,.85fr) minmax(270px,1fr) minmax(300px,1.2fr);gap:16px;align-items:start}.bulk-layout .panel{display:grid;gap:18px;min-height:250px}.bulk-layout h3{font-size:16px;margin:0}.bulk-layout .section-head{margin:0}.bulk-layout .section-head p{color:var(--muted);font-size:12px;margin:5px 0 0}.source-summary{display:flex;align-items:center;gap:12px;border-block:1px solid var(--line);padding:14px 0}.source-icon{width:36px;height:36px;border-radius:7px;display:grid;place-items:center;background:var(--accent-soft);color:var(--accent-strong);font-weight:600}.source-summary strong,.source-summary small{display:block}.source-summary small{font:11px var(--font-mono);color:var(--muted);margin-top:5px}.target-list{max-height:350px;overflow:auto}.target-row{display:flex;justify-content:space-between;align-items:center;gap:12px;min-height:55px;border-bottom:1px solid var(--line)}.target-row strong,.target-row small{display:block}.target-row strong{font-size:13px}.target-row small{font-size:11px;color:var(--muted);margin-top:4px}.target-row small .tag{margin-left:8px}.target-count{border-top:1px solid var(--line);padding-top:13px;color:var(--muted);font-size:12px}.target-count strong,.bulk-footer strong{color:var(--text-strong);font-size:15px;font-variant-numeric:tabular-nums}.field-section{padding-top:16px;border-top:1px solid var(--line)}.field-section h4{font-size:12px;color:var(--muted);margin:0 0 12px}.field-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.field-option{display:flex;align-items:center;gap:8px;min-height:34px;font-size:12px}.bulk-footer{position:sticky;bottom:12px;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 18px;border:1px solid var(--line);border-radius:8px;background:var(--surface);box-shadow:var(--shadow-md);font-size:13px}.bulk-footer .muted{font-size:11px}.bulk-footer .btn{min-width:150px}.error-state{grid-column:1/-1}
@media(max-width:1050px){.bulk-layout{grid-template-columns:repeat(2,minmax(0,1fr))}.fields-panel{grid-column:1/-1}}
@media(max-width:640px){.bulk-heading{align-items:flex-start;flex-direction:column}.bulk-heading h2{font-size:21px}.bulk-layout{grid-template-columns:1fr}.fields-panel{grid-column:auto}.field-options{grid-template-columns:1fr 1fr}.bulk-footer{bottom:0;margin:0 -4px -12px;border-radius:8px 8px 0 0}.bulk-footer .btn{min-width:0}.bulk-footer .muted{display:none}}
</style>
